### ISSUE TITLE
Results after trying to run starrybound for 30 minutes.

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#14]
Crashes once every 2-4 minutes. I am a higher traffic dedi.  Here are some of the stacktraces:

```
Application: StarryboundServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Collections.Generic.Dictionary`2+ValueCollection+Enumerator[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at com.avilance.Starrybound.StarryboundServer.sendGlobalMessage(System.String)
   at com.avilance.Starrybound.Client.doDisconnect(Boolean)
   at com.avilance.Starrybound.Client.forceDisconnect()
   at com.avilance.Starrybound.ForwardThread.run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

```
Application: StarryboundServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Collections.Generic.Dictionary`2+ValueCollection+Enumerator[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at com.avilance.Starrybound.StarryboundServer.sendGlobalMessage(System.String)
   at com.avilance.Starrybound.Client.doDisconnect(Boolean)
   at com.avilance.Starrybound.Client.errorDisconnect(com.avilance.Starrybound.Util.Direction, System.String)
   at com.avilance.Starrybound.ForwardThread.run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

Seems people were getting booted for no reason and that second trace happened a few times.  I gave up for now so I could get you guys some results.

**Comment by saybrook** [comment]
were these issues addressed then?  It says duplicate but doesn't refer to any other issue(s).

**Comment by Crashdoom** [comment]
This seems to be the same (or very similar to the) issue I reported on Mono. It should be addressed in the latest commit.

**Comment by saybrook** [comment]
ok great ill give it a try.  thanks.
