### ISSUE TITLE
New exception

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#17]
```
Application: starrybound_server.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Collections.Generic.Dictionary`2+ValueCollection+Enumerator[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at com.avilance.Starrybound.StarryboundServer.sendGlobalMessage(System.String)
   at com.avilance.Starrybound.Client.doDisconnect(Boolean)
   at com.avilance.Starrybound.Client.errorDisconnect(com.avilance.Starrybound.Util.Direction, System.String)
   at com.avilance.Starrybound.ForwardThread.run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

running the latest (as far as I can tell - downloaded this morning at commit 93

**Comment by Crashdoom** [comment]
Try the latest commit to the development branch: https://github.com/AvilanceLtd/StarryboundServer/tree/development

**Comment by saybrook** [comment]
ok downloading now.  will have it up in the next 30 minutes or so.
