### ISSUE TITLE
cant connect for some reason

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#25]
seemed to work fine all night.. now I just get this:

```
[INFO] [85.228.231.133] Accepting new connection.
[INFO] Loaded persistant user storage for Penelope
[INFO] [Penelope] Dropped by parent Server for ForwardThread Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at com.avilance.Starrybound.Packets.Packet2ConnectResponse.onReceive()
   at com.avilance.Starrybound.ForwardThread.run()
```

Client just says

"Join failed!  No server response received"

**Comment by saybrook** [comment]
man im good at fixing my own issues..

disabling GEOIP in the config fixes this issue.

**Comment by saybrook** [comment]
Was the root cause of this fixed?

**Comment by TheOpalium** [comment]
Accidently closed this, sorry.
