### ISSUE TITLE
Another Fatal Exception

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#34]
The error is so general (and caused by starbound_server crashing with no specifics) that I am going to paste a fair amount of the log leading up to it here: (IP's quickly edited)

```
[DEBUG] [ClientContext]:[Tetris] Failed to parse ClientContextUpdate from Server: System.IndexOutOfRangeException: WorldCoordinate Planet out of range: 90661229
   at com.avilance.Starrybound.Extensions.BinaryReaderEx.ReadStarWorldCoordinate(BinaryReader read)
   at com.avilance.Starrybound.Extensions.BinaryReaderEx.ReadStarCelestialLog(BinaryReader read)
   at com.avilance.Starrybound.ForwardThread.run()
[DEBUG] [EntityCreate]:[Tetris][Player:15786:-7143424]
[DEBUG] [EnvUpdate]:[Tetris] CurLoc:[gamma:-100000108:18172781:-12564786:11:0]
[DEBUG] [SpawnEntity]:[Raptor][ItemDrop:1648]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897789][poisonbroadsword][True]
[INFO] [Planet] [Zachary]: That is so cool
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897775][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897772][poisonbroadsword][True]
[DEBUG] [SpawnEntity]:[Raptor][ItemDrop:39]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356940][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356938][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:98:-6356936][shortswordswoosh1][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356934][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356932][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356930][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356928][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356926][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:98:-6356924][shortswordswoosh1][True]
[DEBUG] [SpawnEntity]:[Raptor][ItemDrop:1692]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356922][bullet-4][True]
[INFO] [Universe] [Robot]: Yep, the things the creators thought of.
[DEBUG] [SpawnEntity]:[Angana][Object:18]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356919][bullet-4][True]
[DEBUG] [SpawnEntity]:[Angana][Object:18]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356917][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356915][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356913][bullet-4][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897747][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356911][bullet-4][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897739][poisonbroadsword][True]
[INFO] [Planet] [perles]: suis dans ton vaisseaux gros xd
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897731][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897725][poisonbroadsword][True]
[INFO] [37.210] Accepting new connection.
[INFO] [37.] Dropped by parent client for End of stream
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897721][poisonbroadsword][True]
[INFO] [Universe] [Jim Oil]: FOUND matter blocks !
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897698][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897695][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897689][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897683][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897677][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897668][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897664][poisonbroadsword][True]
[DEBUG] [SpawnEntity]:[perles][ItemDrop:46]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897659][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897657][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897655][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897652][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897649][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897647][poisonbroadsword][True]
[DEBUG] [WarpCommand]:[perles][3][:0:0:0:0:0][]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897643][poisonbroadsword][True]
[DEBUG] [WarpCommand]:[Tetris][3][:0:0:0:0:0][]
[INFO] [Planet] [Zachary]: I wonder if I can craft and play at the same time
[DEBUG] [EntityCreate]:[Indir][Projectile:114:-6356909][poisonspear][True]
[DEBUG] [SpawnEntity]:[Indir][ItemDrop:2514]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897641][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897639][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897637][poisonbroadsword][True]
[DEBUG] [WarpCommand]:[Tetris][4][:0:0:0:0:0][]
[INFO] [Planet] [Zachary]: Oh, no
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897635][poisonbroadsword][True]
[DEBUG] [EntityCreate]:[Angana][Projectile:119:-5897633][poisonbroadsword][True]
[DEBUG] [WarpCommand]:[Tetris][4][:0:0:0:0:0][]
[DEBUG] [EntityCreate]:[Raptor][Projectile:143:-7077818][woodenarrow][True]
[DEBUG] [WarpCommand]:[Tetris][4][:0:0:0:0:0][]
[INFO] [509] Accepting new connection.
[INFO] [89] Accepting new connection.
[INFO] [107] Dropped by parent client for End of stream
[INFO] [80.1] Dropped by parent client for End of stream
[INFO] [90.29] Dropped by parent client for End of stream
[INFO] [986] Dropped by parent client for End of stream
[INFO] [] Dropped by parent client for End of stream
[INFO] [94.7] Accepting new connection.
[INFO] [99] Accepting new connection.
[INFO] [89..85] Dropped by parent client for End of stream
[INFO] [50.69] Accepting new connection.
[INFO] [94.2107] Dropped by parent client for End of stream
[INFO] [94.107] Accepting new connection.
[INFO] [90.29] Dropped by parent client for End of stream
[INFO] [96.17] Accepting new connection.
[INFO] [50.69] Dropped by parent client for End of stream
[INFO] [90.9] Accepting new connection.
[INFO] [94.2.107] Dropped by parent client for End of stream
[INFO] [24.585] Accepting new connection.
[INFO] [96.4217] Dropped by parent client for End of stream
[INFO] [90.29] Dropped by parent client for End of stream
[INFO] [30] Accepting new connection.
[INFO] [3] Dropped by parent client for End of stream
[INFO] [285] Dropped by parent client for End of stream
[INFO] [96.7] Accepting new connection.
[INFO] [967] Dropped by parent client for End of stream
[INFO] [94.2] Accepting new connection.
[INFO] [141.1369] Accepting new connection.
[INFO] [1439.69] Dropped by parent client for End of stream
[INFO] [94.259.107] Dropped by parent client for End of stream
[INFO] [9407] Accepting new connection.
[INFO] Sending callback data to master server.
[INFO] [37.0] Accepting new connection.
[INFO] [37..21] Dropped by parent client for End of stream
[INFO] [94.107] Dropped by parent client for End of stream
[INFO] [1419.69] Accepting new connection.
[INFO] [141.19] Dropped by parent client for End of stream
[INFO] [98.2.66] Accepting new connection.
[INFO] [98..66] Dropped by parent client for End of stream
[INFO] [Angana] Dropped by parent client for An existing connection was forcibly closed by the remote host
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356907][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356905][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356903][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356901][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356899][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356897][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356895][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356893][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356891][bullet-4][True]
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356889][bullet-4][True]
[INFO] [Tetris] Dropped by parent client for An existing connection was forcibly closed by the remote host
[INFO] [Robot] Dropped by parent client for An existing connection was forcibly closed by the remote host
[INFO] [Robot] is being kicked for Dropped by parent server for An existing connection was forcibly closed by the remote host
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356887][bullet-4][True]
[INFO] [Zachary] Dropped by parent client for An existing connection was forcibly closed by the remote host
[INFO] [perles] Dropped by parent client for An existing connection was forcibly closed by the remote host
[DEBUG] [EntityCreate]:[Indir][Projectile:77:-6356885][bullet-4][True]
[INFO] [Raptor] Dropped by parent client for An existing connection was forcibly closed by the remote host
[INFO] [Indir] Dropped by parent client for An existing connection was forcibly closed by the remote host
[FATAL ERROR] The server has encountered a fatal error and cannot continue. Restarting in 5 seconds.
[FATAL ERROR] Unhandled Exception Occurred: System.NullReferenceException: Object reference not set to an instance of an object.
[INFO] Starting graceful shutdown...
[DEBUG] [Shutdown]:Disconnect all clients.
[INFO] Waiting 10 seconds for all clients to leave.
[DEBUG] [Shutdown]:Requesting starbound_server close.
[DEBUG] [Shutdown]:Waiting for starbound_server to close.
[DEBUG] [Shutdown]:Aborting server thread.
[DEBUG] [Shutdown]:Killing starbound_server process.
[DEBUG] [Shutdown]:Aborting TCP listener.
[INFO] Graceful shutdown complete.
[DEBUG] [Shutdown]:Goodbye.
[INFO] Now restarting...

```

**Comment by ghost** [comment]
Fixed in latest
